language: go

go:
  - 1.8
  - 1.9rc2

install:
  - go get github.com/Masterminds/glide

script:
  - glide install
  - go vet `glide nv`
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
